export const PROJECTS = [
    {
        title: "Agentic OS",
        description: "Built a production-grade multi-agent operating system featuring a speculative fractal RAG pipeline, contextual bandit RL routing for LLMs, and a pgvector-backed knowledge graph memory schema.",
        tag: "LLM Agents & Multi-Agent Systems",
        impact: "Sub-50ms RAG retrieval · 91% retrieval accuracy",
        stack: ["Python", "LangGraph", "LangChain", "pgvector", "FastAPI"],
        github: "https://github.com/savyasachi6/agentic_os",
        live: null,
        featured: true,
    },
    {
        title: "Relational Connectional RAG",
        description: "Component handling user queries, hybrid search, and multi-agent coordination. Built the core retrieval engine combining pgvector similarity search with keyword SQL filtering.",
        tag: "RAG Pipeline",
        impact: "Sub-50ms retrieval · High precision",
        stack: ["Python", "LangChain", "pgvector", "SQL"],
        github: "https://github.com/savyasachi6/relational_connectional_rag",
        live: null,
        featured: false,
    },
    {
        title: "Voice-Controlled LLM Robotics",
        description: "Advanced voice-controlled robotic system using a local LLM for task planning and execution.",
        tag: "Robotics & Local LLMs",
        impact: "Local execution · Voice to Action",
        stack: ["Python", "LLMs", "Robotics", "Speech Recognition"],
        github: "https://github.com/savyasachi6/robot_llm_control",
        live: null,
        featured: false,
    },
    {
        title: "Deep RL Traffic Control",
        description: "A 4-way Traffic Signal Control System that uses deep reinforcement learning (RL) to learn the optimal timing of traffic lights in real-time, minimizing congestion.",
        tag: "Applied RL",
        impact: "Dynamic real-time optimization",
        stack: ["Python", "PyGame", "Deep Reinforcement Learning", "PyTorch"],
        github: "https://github.com/savyasachi6/traffic_control_rl_pygame",
        live: null,
        featured: false,
    },
    {
        title: "Hybrid OCR + A* Sudoku Solver",
        description: "A hybrid Sudoku solver that combines OCR-based visual parsing with A* algorithmic reasoning to showcase structured traversal for logic problems.",
        tag: "Computer Vision & Algorithms",
        impact: "Visual parsing · A* search",
        stack: ["Python", "OCR", "A* Algorithm", "Computer Vision"],
        github: "https://github.com/savyasachi6/TraverseAI-SudokuSolver",
        live: null,
        featured: false,
    },
    {
        title: "NPU Local LLM",
        description: "Project for running Large Language Models locally on an NPU (Intel Core Ultra 9) for high-performance edge inference.",
        tag: "Edge AI & Inference",
        impact: "Hardware acceleration · Local AI",
        stack: ["Python", "LLMs", "Intel NPU", "Edge Computing"],
        github: "https://github.com/savyasachi6/npu_llm",
        live: null,
        featured: false,
    },
    {
        title: "Reward Hacking in Isaac Sim",
        description: "Developed PPO navigation agents in Isaac Sim and ROS2. Engineered custom potential-based C++ reward functions via pybind11, achieving 92% collision-free navigation success.",
        tag: "Applied RL & Robotics",
        impact: "92% collision-free · 38% safety improvement",
        stack: ["Python", "C++", "PyTorch", "ROS2", "Isaac Sim", "pybind11"],
        github: "https://github.com/savyasachi6/nova-carter-rl-ppo-navigation",
        live: null,
        featured: false,
    },
    {
        title: "Distributed DL on TACC Frontera",
        description: "Orchestrated parallel neural network experiments across HPC nodes. Mitigated Lustre Metadata Server saturation by optimizing I/O checkpointing.",
        tag: "High-Performance Computing",
        impact: "57,000 → 1 I/O ops · 45min → <2min checkpoint",
        stack: ["Slurm", "MPI", "HDF5", "Lustre", "C++", "Python"],
        github: "https://github.com/savyasachi6/DL-ParallelTraining",
        live: null,
        featured: false,
    }
];
