export const PROJECTS = [
    {
        title: "Agentic OS",
        description: "Built a production-grade multi-agent operating system featuring a speculative fractal RAG pipeline, contextual bandit RL routing for LLMs, and a pgvector-backed knowledge graph memory schema.",
        tag: "LLM Agents & Multi-Agent Systems",
        impact: "Sub-50ms RAG retrieval · 91% retrieval accuracy",
        stack: ["Python", "LangGraph", "LangChain", "pgvector", "FastAPI"],
        github: "https://github.com/savyasachi6/relational_connectional_rag",
        live: null,
        featured: true,
    },
    {
        title: "Reward Hacking in Isaac Sim",
        description: "Developed PPO navigation agents in Isaac Sim and ROS2. Eliminated the 'Vibrating Agent' local optima artifact by engineering custom potential-based C++ reward functions via pybind11, achieving 92% collision-free navigation success.",
        tag: "Applied RL & Robotics",
        impact: "92% collision-free · 38% safety improvement",
        stack: ["Python", "C++", "PyTorch", "ROS2", "Isaac Sim", "pybind11"],
        github: "https://github.com/savyasachi6/nova-carter-rl-ppo-navigation",
        live: null,
        featured: false,
    },
    {
        title: "MDS Saturation on Stampede3",
        description: "Orchestrated parallel neural network experiments across 560+ Sapphire Rapids HBM nodes. Mitigated Lustre Metadata Server saturation by re-engineering 57,000 I/O operations down to 1 via node-local /tmp checkpointing.",
        tag: "High-Performance Computing",
        impact: "57,000 → 1 I/O ops · 45min → <2min checkpoint",
        stack: ["Slurm", "MPI", "HDF5", "Lustre", "C++", "Python"],
        github: "https://github.com/savyasachi6/DL-ParallelTraining",
        live: null,
        featured: false,
    },
    {
        title: "SNAT Port Exhaustion Mitigation",
        description: "Diagnosed Azure App Service SNAT exhaustion for 100k+ daily API requests. Optimized SQL Server indexing strategy and refactored .NET microservices on Kubernetes, achieving 99.99% service availability.",
        tag: "Distributed Systems",
        impact: "57% latency reduction · 70% fewer outbound TCP connections",
        stack: ["C#", ".NET", "SQL Server", "Azure", "Kubernetes"],
        github: "https://github.com/savyasachi6",
        live: null,
        featured: false,
    },
    {
        title: "Productionizing Deep Learning Inference",
        description: "Integrated PyTorch-based deep learning models into production infrastructure. Applied ONNX Runtime optimization and INT8 quantization across a platform serving 10,000+ daily prediction requests.",
        tag: "MLOps & Inference",
        impact: "<100ms inference latency · 75% model size reduction",
        stack: ["PyTorch", "ONNX", "Kubernetes", "Python", "Docker"],
        github: "https://github.com/savyasachi6",
        live: null,
        featured: false,
    },
];
